### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by Semigradsky** [twisty/formsy-react-components#18]
How about improve performance with [`pure-render-mixin`](https://facebook.github.io/react/docs/pure-render-mixin.html)?

**Comment by twisty** [comment]
Thanks for the suggestion... worth a look. Would be interesting to benchmark this in a "typical" scenario.

I'm also keeping an eye on christianalfoni/formsy-react#154. 😀

**Comment by twisty** [comment]
Also: [PureRenderMixin does not work on Formsy managed components](christianalfoni/formsy-react#134).

**Comment by twisty** [comment]
Tracking some perf stuff:

- [x] christianalfoni/formsy-react#134
- [x] christianalfoni/formsy-react#154
- [ ] christianalfoni/formsy-react#227
- [x] christianalfoni/formsy-react#252

**Comment by twisty** [comment]
This one has been hanging around a while with no activity, so closing.

**Comment by bipulkmr** [comment]
So are you telling we cannot use this formsy then for larger components ?

**Comment by twisty** [comment]
I'd say that the performance is good enough for most people.

But yes, if you want a form with 30-100 controls, it may be that `formsy-react` isn't the best fit.
